name: Flutter Build
on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart pub get
      - run: flutter build windows
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows release
          path: |
            build/windows/runner
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Install project dependencies
        run: dart pub get
      - name: Build artifacts
        run: flutter build linux
